/**
 * src/audio/presets.ts
 *
 * Named aesthetic bundles for the synth + cassette engine.
 * Each preset is a partial Settings object that gets applied via store.set().
 * 'custom' is not in this table — it means "user has diverged from a preset".
 */

import type { Settings } from "../store/schema.js";

export const FM_PRESETS: Record<string, Partial<Settings>> = {
  none: {
    "synth.fmIndexBase": 0,
    "synth.fmIndexScale": 0,
    "synth.fmRatioDrift": 0,
    "synth.fmStereoWidth": 0,
    "synth.fmPluckRatio": 1,
  },
  subtle: {
    "synth.fmIndexBase": 0.05,
    "synth.fmIndexScale": 0.8,
    "synth.fmRatioDrift": 0.01,
    "synth.fmStereoWidth": 0.3,
    "synth.fmPluckRatio": 2,
  },
  warm: {
    "synth.fmIndexBase": 0.15,
    "synth.fmIndexScale": 2.4,
    "synth.fmRatioDrift": 0.04,
    "synth.fmStereoWidth": 0.75,
    "synth.fmPluckRatio": 2,
  },
  bright: {
    "synth.fmIndexBase": 0.3,
    "synth.fmIndexScale": 4.5,
    "synth.fmRatioDrift": 0.08,
    "synth.fmStereoWidth": 0.9,
    "synth.fmPluckRatio": 3,
  },
  harsh: {
    "synth.fmIndexBase": 0.8,
    "synth.fmIndexScale": 7.0,
    "synth.fmRatioDrift": 0.15,
    "synth.fmStereoWidth": 1.0,
    "synth.fmPluckRatio": 5,
  },
};

export const GLIDE_PRESETS: Record<string, Partial<Settings>> = {
  none: {
    "synth.glideMin": 0.001,
    "synth.glideMax": 0.001,
    "synth.glideSpread": 0,
  },
  tight: {
    "synth.glideMin": 0.005,
    "synth.glideMax": 0.3,
    "synth.glideSpread": 0.5,
  },
  smooth: {
    "synth.glideMin": 0.01,
    "synth.glideMax": 2.0,
    "synth.glideSpread": 1.0,
  },
  slow: {
    "synth.glideMin": 0.05,
    "synth.glideMax": 5.0,
    "synth.glideSpread": 2.0,
  },
};

export const CASSETTE_PRESETS: Record<string, Partial<Settings>> = {
  none: {
    "cassette.midBoostDb": 0,
    "cassette.masterLPHz": 20000,
    "cassette.satAmount": 0,
    "cassette.satWet": 0,
    "cassette.tapeDelayMs": 60,
    "cassette.tapeDelayFb": 0,
    "cassette.tapeDelayWet": 0,
    "cassette.reverbWet": 0,
    "cassette.noiseGain": 0,
    "cassette.wowDepthCents": 0,
    "cassette.flutterDepthCents": 0,
  },
  clean: {
    "cassette.midBoostDb": 0,
    "cassette.masterLPHz": 18000,
    "cassette.satAmount": 2,
    "cassette.satWet": 0.1,
    "cassette.tapeDelayMs": 60,
    "cassette.tapeDelayFb": 0.05,
    "cassette.tapeDelayWet": 0.0,
    "cassette.reverbWet": 0.0,
    "cassette.noiseGain": 0.002,
    "cassette.wowDepthCents": 0,
    "cassette.flutterDepthCents": 0,
  },
  warm: {
    "cassette.midBoostDb": 3,
    "cassette.masterLPHz": 11000,
    "cassette.satAmount": 7,
    "cassette.satWet": 0.35,
    "cassette.tapeDelayMs": 130,
    "cassette.tapeDelayFb": 0.2,
    "cassette.tapeDelayWet": 0.12,
    "cassette.reverbWet": 0.08,
    "cassette.noiseGain": 0.01,
    "cassette.wowDepthCents": 5,
    "cassette.flutterDepthCents": 1.0,
  },
  lofi: {
    "cassette.midBoostDb": 4,
    "cassette.masterLPHz": 6000,
    "cassette.satAmount": 14,
    "cassette.satWet": 0.6,
    "cassette.tapeDelayMs": 80,
    "cassette.tapeDelayFb": 0.35,
    "cassette.tapeDelayWet": 0.22,
    "cassette.reverbWet": 0.06,
    "cassette.noiseGain": 0.055,
    "cassette.wowDepthCents": 12,
    "cassette.flutterDepthCents": 4.0,
  },
  vintage: {
    "cassette.midBoostDb": 6,
    "cassette.masterLPHz": 8000,
    "cassette.satAmount": 12,
    "cassette.satWet": 0.55,
    "cassette.tapeDelayMs": 180,
    "cassette.tapeDelayFb": 0.28,
    "cassette.tapeDelayWet": 0.25,
    "cassette.reverbWet": 0.22,
    "cassette.noiseGain": 0.03,
    "cassette.wowDepthCents": 14,
    "cassette.flutterDepthCents": 2.5,
  },
  live: {
    "cassette.midBoostDb": 5,
    "cassette.masterLPHz": 15000,
    "cassette.satAmount": 5,
    "cassette.satWet": 0.25,
    "cassette.tapeDelayMs": 60,
    "cassette.tapeDelayFb": 0.1,
    "cassette.tapeDelayWet": 0.0,
    "cassette.reverbWet": 0.0,
    "cassette.noiseGain": 0.005,
    "cassette.wowDepthCents": 2,
    "cassette.flutterDepthCents": 0.5,
  },
};

export const PRESETS: Record<string, Partial<Settings>> = {
  lush: {
    "synth.articulationBass": 0,
    "synth.articulationMid": 0,
    "synth.articulationTreble": 0,
    "synth.pulseRateBass": 0,
    "synth.pulseRateMid": 0,
    "synth.pulseRateTreble": 0,
    "synth.fmIndexBase": 0.15,
    "synth.fmIndexScale": 2.4,
    "synth.glideMax": 2.0,
    "cassette.reverbWet": 0.18,
    "cassette.tapeDelayWet": 0.18,
    "cassette.satAmount": 8,
  },
  drone: {
    "synth.articulationBass": 0,
    "synth.articulationMid": 0,
    "synth.articulationTreble": 0,
    "synth.pulseRateBass": 0,
    "synth.pulseRateMid": 0,
    "synth.pulseRateTreble": 0,
    "synth.fmIndexBase": 0.05,
    "synth.fmIndexScale": 1.2,
    "synth.glideMax": 3.5,
    "cassette.reverbWet": 0.3,
    "cassette.tapeDelayWet": 0.22,
    "cassette.satAmount": 5,
  },
  staccato: {
    "synth.articulationBass": 0.65,
    "synth.articulationMid": 0.65,
    "synth.articulationTreble": 0.65,
    "synth.pulseRateBass": 2,
    "synth.pulseRateMid": 2,
    "synth.pulseRateTreble": 2,
    "synth.fmIndexScale": 1.8,
    "synth.glideMax": 0.5,
    "cassette.reverbWet": 0.04,
    "cassette.tapeDelayWet": 0.05,
    "cassette.satAmount": 10,
  },
  percussive: {
    "synth.articulationBass": 0.95,
    "synth.articulationMid": 0.95,
    "synth.articulationTreble": 0.95,
    "synth.pulseRateBass": 4,
    "synth.pulseRateMid": 4,
    "synth.pulseRateTreble": 4,
    "synth.fmPluckRatio": 3,
    "synth.glideMax": 0.2,
    "cassette.reverbWet": 0.02,
    "cassette.tapeDelayWet": 0.03,
    "cassette.satAmount": 12,
  },
  bell: {
    "synth.articulationBass": 0.85,
    "synth.articulationMid": 0.85,
    "synth.articulationTreble": 0.85,
    "synth.pulseRateBass": 0,
    "synth.pulseRateMid": 0,
    "synth.pulseRateTreble": 0,
    "synth.fmPluckRatio": 7,
    "synth.carrierTypePluck": "sine",
    "synth.glideMax": 0.3,
    "cassette.reverbWet": 0.25,
    "cassette.tapeDelayWet": 0.1,
    "cassette.satAmount": 6,
  },
};
